### ISSUE TITLE
Potential Violation Detected

### ISSUE THREAD

**Issue by assignguard-support** [nikhilravikrishnan/AudioCaptioning#8]
Hey nikhilravikrishnan!

This repository has been flagged as containing material which potentially infringes upon an academic copyright or an institution's academic integrity policies.

At your earliest convenience, please do one of the following:
  - disable public access to your repository see [repository access settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility)
  - remove any content could be in violation of copyright law
  - remove any content could be in violation of an institution's academic integrity policy

Please feel free to continue any discussion here. Thanks!

**Comment by assignguard-support** [comment]
:wave: gentle reminder!

**Comment by fourpenny** [comment]
We are discussing this with our course instructor to see if there is an issue. In the future, this product would benefit from more specific details about potential problems with a repo rather than a generic message such as this one.

**Comment by fourpenny** [comment]
No issues after discussing with Dr. Xu- we are free to keep our code public if desired.
